files/mongodb.service, handlers/main.yml, tasks/configure.yml, tasks/install.deb.yml
Hi,
First, thanks for your role. I was trying to make it work on Debian Jessie and discovered the incompatibility of MongoDB with systemd. :-/
I performed some changes in the role to make it work. It's more a workaround in waiting MongoDB changes (https://jira.mongodb.org/browse/SERVER-7285).
Can you please merge ?
Thanks
=> fixing service fail with systemd

files/mongodb.service
In tasks/install.yml configuration template file is copied to /etc/mongod.conf. This means that modifications to Mongo configuration are not applied.
=> Use proper Mongo configuration file

tasks/auth_initialization.yml
To avoid the error mentioned in https://github.com/UnderGreen/ansible-role-mongodb/issues/2#issuecomment-158137414
=> Adding wait after mongodb restart

tasks/auth_initialization.yml
This PR fixes the following issues https://github.com/UnderGreen/ansible-role-mongodb/pull/39#issue-118406174
=> Fixes for the wait_for issue

tasks/replication.yml, tasks/replication_init_auth.yml
It resolves part of this issue #37
=> Fixed "ERROR! 'mongodb_replication_params' is undefined"

README.md
I'm sorry for how trivial this is. 
I ignored it successfully for 2 days.
=> Most trivial change I've ever made

.travis.yml, README.md, defaults/main.yml, meta/main.yml, tasks/install.debian.yml, tasks/install.redhat.yml, tasks/main.yml, templates/mongod.conf.j2, templates/mongod_init.conf.j2, templates/mongodb.repo.j2, vars/RedHat.yml
This is a preliminary pull request, just to get some early feedback around the approach I've taken to this.
Far more testing is also required before I'd be satisfied with this.
=> Support for RHEL and CentOS platforms

tasks/configure.yml, templates/mongod.conf.j2, templates/mongod_init.conf.j2
The new template will be able to configure systemLog options based in the destination.
=>  Modifying mongod conf template.

tests/scripts/before_install.sh
`docker-py` has to be replaced with `docker` to make tests working again.
=> Trying to fix tests

README.md, defaults/main.yml, templates/mongod.conf.j2
Fixed a stupid typo 
Removed static filetype for pem certs
added cache setting for wiredtiger
=> fix typo / fixed filetype extension / added wiredtiger cache setting

tasks/configure.yml, tasks/install.debian.yml, templates/mongod.conf.j2
Deprecation warnings resolved in debian tasks.
Tests under ubuntu 18.04 ok.
=> Deprecation for apt resolved for debian

tasks/configure.yml
Fix role when systemlog_destination is configurated to "syslog"
=> Closes UnderGreen/ansible-role-mongodb#102

.travis.yml, README.md, defaults/main.yml, tasks/install.debian.yml, tasks/install.redhat.yml, tests/host_vars/mongo3.yml, vars/Debian.yml, vars/RedHat.yml, vars/Ubuntu.yml
Continued the work of @ftx in #134 
Closes #123
=> Support V4.0

.travis.yml, README.md, meta/main.yml, tasks/install.amazon.yml, tasks/main.yml, tests/Dockerfile.amazonlinux_2-builded, vars/Amazon.yml
Making this role available for amazonlinux users.
The tests were expanded as well.
=> Adding amazonlinux support

defaults/main.yml, tasks/main.yml, tasks/replication.yml, tasks/replication_init_auth.yml
Fix errors if set `mongodb_net_ssl_mode: requireSSL`
=> Add correct support mode requireSSL.

tasks/auth_initialization.yml
Hello,
Thank you for this role; just a quick fix because it looks weird to see default user names displayed in the tasks list when you have customized them :)
=> Use provided username in task name

tasks/configure.yml
Fix issue https://github.com/UnderGreen/ansible-role-mongodb/issues/192
=> Fix log permissions

.gitignore, .travis.yml, defaults/main.yml, handlers/main.yml, tasks/configure.yml, tasks/disable_transparent_hugepages.yml, tasks/install.debian.yml, tasks/main.yml, tasks/mms-agent.yml, tasks/replication.yml, templates/mongodb.service.j2, tests/Dockerfile.amazonlinux_2-builded, tests/Dockerfile.centos_6-builded, tests/Dockerfile.centos_7-builded, tests/Dockerfile.debian_8-builded, tests/Dockerfile.debian_9-builded, tests/Dockerfile.ubuntu-upstart_14_04-builded, tests/Dockerfile.ubuntu_16_04-builded, tests/Dockerfile.ubuntu_18_04-builded, tests/callback_plugins/profile_tasks.py, tests/files/etc/apt/apt.conf.d/proxy.conf, tests/files/etc/environment, tests/files/etc/squid/squid.conf, tests/group_vars/all.yml, tests/host_vars/mongo1.yml, tests/host_vars/mongo2.yml, tests/scripts/before_install.sh, tests/site.yml
Changes:
* Fix handlers and systemd unit
* Add proxy cache of apt, yum and pip for tests
* Replace split launch of tests to general launch of test for all hosts of MongoDB cluster
=> Fix handlers and systemd unit, speed up tests

README.md, defaults/main.yml, templates/mongod.conf.j2
=> add support for extending config

templates/mongodb.service.j2
=> MongoDB starts before the network on Debian system

tasks/install.amazon.yml, tasks/install.redhat.yml
Fixed typo. "=" symbol replaced with "-" and it allows to install exact version of mongodb package.
#202
=> [#202] - Fix to have ability to install exact version of mongodb

library/mongodb_replication.py, tasks/install.amazon.yml, tasks/install.debian.yml, tasks/install.redhat.yml, vars/Amazon.yml, vars/Debian.yml, vars/RedHat.yml, vars/Ubuntu.yml
If you want, I can add tests for Python 3, but the total test execution time will then increase.
=> Add support python3 as ansible_python_interpreter.

molecule/default/molecule.yml, tasks/auth_initialization.yml
=> Use bindip for mongodb_user

defaults/main.yml, meta/main.yml
=> Enable javascript on server-side by default
