handlers/main.yml
tasks/configure.yml
tasks/install.deb.yml

Hi,
This fixes a regression caused by the introduction of systemd in the role. It works on Debian Wheezy. Sorry for the trouble.
I also changed systemd check detection on the binary instead of a folder path because it looks like more or less present in standard Wheezy distribution. The binary requires to have systemd package installed, so it should be better.
Thanks

fix regression on non systemd debian

---

tasks/configure.yml
tasks/install.deb.yml
tasks/main.yml

Updating systemd detection by getting PID 1 command line instead of
checking systemd folder. This to avoid issues with Docker for example.

fixing systemd issue with docker

---

templates/mongod.conf.j2

because  quotaFiles option  implies --quota . 
quotaFiles   "number of files allowed per db, implies --quota"  
see mongodb source code : 
https://github.com/mongodb/mongo/blob/ef7f17be8085488ba965286fb97927a7ce3600e7/src/mongo/db/mongod_options.cpp#L223

don't set  quotaFiles  if mongodb_conf_quota is false

---

README.md
defaults/main.yml
handlers/main.yml
tasks/configure.yml
tasks/mms-agent.yml

Hi,
Docker may not be able to start services (including MongoDB) when coupled with Systemd. That's why it's better to be able to manage the service.
This PR give the possibility to let the role manage or not the service.
Can you please merge and make a new version ?
Thanks

feat: adding service managment

---

README.md
defaults/main.yml
tasks/install.deb.yml

It turned out that `python-pymongo` package for Ubuntu 14.04 contains outdated `pymongo` module (version 2.6.3) which uses obsolete authentication schema incompatible with MongoDB v2.6.9. This way, when it's used to create MongoDB users, the further authentication fails without [upgrading auth schema](http://docs.mongodb.org/manual/reference/command/authSchemaUpgrade/#dbcmd.authSchemaUpgrade) manually on each DB server.
So this PR includes an ability to install latest PyMongo (2.8 at the moment) via [PIP](https://pip.pypa.io/en/latest/) which works fine with latest MongoDB v2.6.9.

Ability to install PyMongo from PIP

---

README.md
defaults/main.yml
handlers/main.yml
tasks/configure.yml
tasks/mms-agent.yml

Hi,
I encounter an issue when I do not want the service to be managed by Ansible, but do not get a running instance of Mongo.
This fix will temporary start a Mongo instance, apply what is has to do and then kill the instance. Can you please review it and merge if ok.
Thanks

fixing creation user fail when not managing service and typo

---

README.md
defaults/main.yml
files/disable_thp.sh
tasks/configure.yml

http://docs.mongodb.org/manual/reference/transparent-huge-pages/#in-etc-rc-local-alternate
https://jira.mongodb.org/browse/DOCS-2131
Can be disabled by setting `mongodb_disable_thp ` var to `false`

Disable Linux THP on Debian distros

---

README.md
defaults/main.yml
tasks/configure.yml

Hi,
In some case like Cloud or Docker, it's useful to use persistent disk for mongodb. A possible problem can occur. It is to get a different a different uid/gid which can lead to read/write problem at start.
That's why I added this to force the uid and gid to avoid issue in that case.
Thanks to merge this PR

can set uid and gid of mongodb user

---

tasks/configure.yml

Hi,
Changing the uid is a good thing when set on a fresh mongo install but it's better to reset rights to avoid issues on an existing instance.

feature: adding right reset when modifying uid

---

tasks/auth_initialization.yml

with latest update, a mongodb restart couldn't work properly. New checks
have been added to fix the issue

fix issue with unmanaged service

---

tasks/install.deb.yml

More and more physical servers are running on numa infrastructure. To
get best performances, numactl is required.

Adding numactl package

---

tasks/install.deb.yml

It appears that standard mongo install process on debian doesn't create the /data/db directory. This prevents mongo process from starting and required manual job on the server.
With this fix the /data/db directory will be created by ansible during install process.

Ensure /data/db directory on debina

---

defaults/main.yml
tasks/install.deb.yml

remove when conditional for the same
these steps were skipped when i specified my own mongodb-package

parameterize apt key and apt repo url variables

---

tasks/install.deb.yml

The task that ensures the database directory is created with correct ownership is hard-coded to the default value, `/data/db`.  This means supplying a value for `mongodb_conf_dbpath` changes the configuration, but will (likely) result in errors when MongoDB attempts to use the location.  This PR simply supplies the variable name into the task so that things work as expected.

Use mongodb_conf_dbpath rather than a hard-coded path name

---

library/mongodb_replication.py
tasks/replication.yml
tasks/replication_init_auth.yml

Currently `ansible-role-mongodb` does not support replicaset member configuration options as "hidden" and "priority".
This commit attempts to solve the problem described above. Support for attributes "hidden" and "priority" has been added, and can be established in the following way:
mongodb_replication_params:
- { host_name: mongo-hidden, priority: 0, hidden: true }
Fixes #41

Add support for hidden repl members and priorities

---

templates/mongod.conf.j2

According to MongoDB documentation (https://docs.mongodb.org/v3.0/tutorial/enable-internal-authentication/), "enabling internal authentication (in a replicaset) enables access control". Therefore, if MongoDB is configured without authentication (`auth = no`) a `keyFile` line must not appear in the configuration file.
This commit attempts to solve the problem described above. An extra check has been added to ensure the `keyFile` configuration option is added only if replicaset authorization _and_ authentication is enabled.
Fix #43

Fix replicaset config without authentication

---

tasks/main.yml

If we use only one node without replication, we're get this error:
```
TASK [greendayonfire.mongodb : Replication configuration] **********************
fatal: [mongo]: FAILED! => {"failed": true, "msg": "ERROR! 'mongodb_replication_params' is undefined"}
```
Its raised by `replication.yml`, which applied to node, although replication is disabled. It caused by wrong conditionals in `tasks/main.yml`. In previous version **`replication.yml` launched when `mongodb_conf_replSet` is defined, but it always defined (but empty) in `defaults/main.yml`**. I suggest change this condition (and replication_init_auth condition) from `mongodb_conf_replSet is defined` to `mongodb_conf_replSet != ''` or simple `mongodb_conf_replSet`.

Resolved error in single-node installation

---

tasks/configure.yml
tasks/install.deb.yml

Looks like when this variable was introduced, this particular task was
missed.
This has also been moved to the configuration stage, since it seems to
fit with the task for ensuring the log directory exists, too.

Ensure dbpath directory has configurable owner

---

tasks/configure.yml

Since the service could have been stopped manually (outside Ansible) we should ensure that the service is started before waiting for the port to come up.

Ensure service is started

---

tasks/install.deb.yml
tasks/main.yml

I identified two script tasks which prevented the role to be used in check_mode. I added an "always_run = yes" to them as I am fairly certain those task are read-only / side-effect free. So they can be run in check_mode without negative consequences.

Enabling check_mode

---

tasks/install.deb.yml

The role checks if the system is running or not systemd. It checks the name of the process with PID1, and if it contains the string "systemd" assumes that the host is systemd-based. Unfortunately that check fails in Ubuntu Xenial:
```
vagrant@mongo-xenial:~$ cat /proc/1/cmdline
/sbin/init
```
A better approach may be to check if /sbin/init is a symlink or a binary. In systemd-based systems (e.g. Ubuntu Xenial), /sbin/init is a symlink to the systemd binary:
```
vagrant@mongo-xenial:~$ file /sbin/init
/sbin/init: symbolic link to /lib/systemd/systemd
```
In Ubuntu Trusty /sbin/init is a binary:
```
vagrant@mongo-trusty:~$ file /sbin/init
/sbin/init: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, …
```

Fix systemd test for Ubuntu Xenial

---

tasks/auth_initialization.yml
tasks/main.yml

This role prints passwords in Ansible outputs (e.g. when creating users, etc.). This is a problem because passwords must never appear in plaintext under any circumstances.
This commit attempts to fix the problem described above. The option "no_log: true" has been added to tasks which may print passwords during Ansible execution.

Do not show passwords in Ansible output

---

handlers/main.yml
tasks/install.deb.yml
templates/mongod.conf.j2
templates/mongod_init.conf.j2

Commit #d9393b1 did not completely fixed the systemd-related issues. The handler `reload systemd` has  a `when` clause which fails in systemd-based systems.
This commit attempts to fix the problem described above. The `when` clause in the handler `reload systemd` has been fixed. Some facts has been added in the install playbook, in order to make the code more simple and easier to maintain.

Fix (again) Systemd support

---

files/mongodb.service

The default service FD limit of 1024 is not sufficient for MongoDB
deployments that handle thousands of client connections and
databases.

Increase the file descriptor limit for the systemd service.

---

tasks/auth_initialization.yml
tasks/configure.yml

Hello! I'm trying to deploy instance of MongoDB to Digital Ocean and providing var `mongodb_net_bindip` with two ip's: localhost and private droplet address, gives me timeouts as described [here](https://github.com/UnderGreen/ansible-role-mongodb/issues/71) and [here](https://github.com/UnderGreen/ansible-role-mongodb/issues/46). 
I have replaced raw string with loop and it works fine for me. 
Could you please take a look and accept if everything is ok?

Fixed issue with multi-port binding timeouts

---

tasks/main.yml

Bugfix: If using a custom port, checking if the admin user exists always return False, forcing a mongodb db restart to create it even if it is already existing, and an other restart to re-enable authentication.

Add custom port in command to check if admin user exists

---

README.md
defaults/main.yml
tasks/install.deb.yml
vars/Debian.yml
vars/Ubuntu.yml

Hi,
This PR updates mongo repositories and repo key id for mongo 3.4.
Succesfully tested on Ubuntu 16.04 .

add mongo 3.4 support

---

defaults/main.yml
templates/mongod.conf.j2
templates/mongod_init.conf.j2

This should be configurable to be set to `reopen` when normal external log rotate is used.

add systemLog.logRotate option as configurable

---

README.md
defaults/main.yml
tasks/install.debian.yml
tasks/install.redhat.yml

Due to issue #113 I created a new variable `mongodb_pymongo_pip_version` to allow users to choose which version to get from pip. `3.6.1` works fine

Allow user to choose PyMongo version when using pip

---

templates/mongodb.repo.j2

When overriding mongodb repository settings, ignore empty gpgkey entries. (needed e.g. when using `merge_behavior=hash`).

ignore empty mongodb repository gpgkey settings

---

README.md

ansible-galaxy install greendayonfire.mongodb
- downloading role 'mongodb', owned by greendayonfire
[WARNING]: - greendayonfire.mongodb was NOT installed successfully: - sorry, greendayonfire.mongodb was not found
on https://galaxy.ansible.com.

Update to Github Readme

---

defaults/main.yml
templates/mongod.conf.j2

We needed a mongodb replication cluster with internode ssl , this is a quick way to add it

Added ssl config support in config template

---

tasks/mms-agent.yml

`mongodb_mms_agent_loaded` gets redefined even when the next task is skipped. Putting installation task right next do download one fixes the issue.

Put tasks in the right order

---

README.md
defaults/main.yml
templates/mongod.conf.j2
templates/mongod_init.conf.j2

Hello...
I had the specific need to set up a Mongo Cluster with the DirectorPerDB option set to true. I added the parameter to the defaults (default to false as per Mongo Default) and unconditionally added the resulting output to mongod_init.conf.j2 and mongod.conf.j2.
It could be argued to make the inclusion of the parameter in the config files conditional on it being set to true, but I think that explicit is better (and simpler).
Received minimal testing by deploying with the option set to true and to false on a newly deployed VM and it does, what it is supposed to.
Also added a line to the README.md.
Feedback or merge appreciated :-)
kind regards,
Patrick

Add "DirectoryPerDB" parameter

---

README.md
defaults/main.yml
files/disable-transparent-hugepages.init
files/disable-transparent-hugepages.sh
tasks/disable_transparent_hugepages.yml
tasks/install.debian.yml

This PR adds a variable to allow transparent hugepages deactivation using a systemd service.
I guess it can also work on redhat based system since deactivate script came from mongodb redhat documentation: https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

Add a variable to disable transparent hugepages

---

tasks/configure.yml

When changing the default data directory path on systems with SELinux, we must also set the SELinux type on that directory.

Set selinux type on data directory

---

README.md
tasks/main.yml

Add functionality to create oplog users to address https://github.com/UnderGreen/ansible-role-mongodb/issues/126
Feel free to change and modify at will

Oplog user creation

---

README.md

Currently backup user password is not specified in the list of variables required to be changed on production. This may result some users having insecure password `passw0rd` for a backup user in their production environment.

Require backup user password to be changed on production

---

tasks/install.debian.yml

Fix "No package matching 'mongodb' is available" error

Apt update cache before installing mogodb

---

defaults/main.yml
tasks/install.debian.yml

Allows to easily upgrade MongoDB by overriding the `mongodb_package_state` variable.
Example:
```
ansible-playbook -i inventory site.yml -e mongodb_package_state=latest
```

Add variable to customize mongodb package state

---

tasks/replication.yml
tasks/replication_init_auth.yml

Add `build_indexes` and `votes` options of `mongodb_replication` module. If not provided, options are omitted so this PR is backward compatible.
Use case:
Hidden member with no votes and no index built:
```
mongodb_replication_params:
- host_name: "mongodb-slave.internal.domain"
build_indexes: false
hidden: true
priority: 0
votes: 0
```

Allow more options in replication params

---

tasks/install.debian.yml

Change permissions of `/lib/systemd/system/mongodb.service` from 640 to 644 to avoid warning  message in syslog during `systemctl daemon-reload`.
```
May 15 14:35:24 web01 systemd[1]: Configuration file /lib/systemd/system/mongodb.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
```

Fix systemd service file permissions

---

.travis.yml
tasks/install.debian.yml
tests/group_vars/all.yml

- mongodb package name for 18.04 is 'mongodb-org'
- package name 'mongodb' will install mongodb
from ubuntu repo which is 3.6 currently and is
not a recommended way.

Mongodb package name fix for ubuntu 18.04

---

defaults/main.yml
templates/mongod.conf.j2

Add `mongodb_cloud_monitoring_free_state` variable which controls `cloud.monitoring.free.state` in `/etc/mongod.conf`.
This option is described in https://docs.mongodb.com/manual/reference/configuration-options/#cloud-options.
By setting `mongodb_cloud_monitoring_free_state` to `off` you get rid of the annoying message added in MongoDB shell 4.0.X:
```
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).
The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.
To enable …
```

Add option to configure free monitoring

---

templates/mongod_init.conf.j2

If `mongodb_wiredtiger_directory_for_indexes: true`, an error occurs:
```
STORAGE  [initandlisten] exception in initAndListen: InvalidOptions: Requested option conflicts with current storage engine option for directoryForIndexes; you requested true but the current server storage is already set to false and cannot be changed, terminating
```

Fix init template

---

tasks/install.debian.yml

When installing mongodb-org packages on Debian/Ubuntu the daemon name is set to "mongod" but the .service file is unconditionally installed as "mongodb.service". This PR ensures, that the systemd file (and the accompanying symlink) are installed as "mongodb_dameon_name.service". Otherwise installation fails with 
fatal: [tmongo-02]: FAILED! => {"changed": false, "msg": "Could not find the requested service mongod: host"}
for every host, as the handler tries to restart mongod, but systemd only sees mongodb.
Minimally tested against Ubuntu 16.04/Mongo 3.4.

Ensure the systemd file is created under the correct name on Debian/Ubuntu

---

tasks/install.debian.yml

Since ansible 2.7+, it is appearently required to have `setuptools` installed on the target hosts to use the `pip` module (see [this issue](https://github.com/ansible/ansible/issues/47361)).
Note: I tested only on debian 9, but I assume the `python-setuptools` package is available in other debians...

Add setuptools install

---

README.md

Hello,
I think it's important to advertise the backup user too in readme, otherwise people using this role might forget it and have this account provided with defaults, which is a security risk.
Regards,

Add backup user in readme

---

handlers/main.yml

I had a weird bug where after copying the mongod.conf file, the handler was not ran properly.
Not sure why but fixing this syntax to match yaml default format seems to fix the issue.

Fixed handlers yaml format

---

README.md
tasks/install.amazon.yml
tasks/install.redhat.yml
vars/Amazon.yml
vars/RedHat.yml

This role supports 4.2 but README.md is not updated yet.
And changed mongodb_version to 4.2 because it supprts 4.2 as default.

Fix README.md file. Support MongoDB 4.2 as default.

---

README.md

Version 3.6 is not longer supported on Ubuntu 18.04 and Amazon Linux 2: https://docs.mongodb.com/manual/installation/#mongodb-supported-platforms

Update 3.6 version info in support matrix

---

README.md
defaults/main.yml
tasks/install.amazon.yml
tasks/install.debian.yml
tasks/install.redhat.yml
templates/mongodb.service.j2

Hello,
Add a variable allowing to disable NUMA.
Default behaviour remains the same as before (enabled).
My use case is NUMA is not available inside a Docker container run on Github Actions.

Make NUMA optional

---

tasks/main.yml

Task: "create oplog user with replicaset" (task/main, line 124) has "no_log: false" which exposes the oplog user and it's password during an ansible play.
changed no_log to true instead of false
Fixes #221

no_log = true for 'create oplog user with replicaset'

---

defaults/main.yml

As if you are behind a firewall standard keyserver port 11371 may be filtered

Use port 80 for Ubuntu keyserver

---

tasks/install.amazon.yml
tasks/install.debian.yml
tasks/install.redhat.yml

In latest ansible versions the mongodb_major_version
becomes a float. So we need to explicitly make it a
string.

mongodb_major_version needs to be a string

---

defaults/main.yml
tasks/install.debian.yml

Apt-key doesn't work behind proxies when fetching from keyservers

Allow fetching apt keys from url
